spring.application.name=OT Management System

# Server
server.port=3010

# Database (USE THIS)
#spring.datasource.url=jdbc:mysql://localhost:3306/ot_db
#spring.datasource.username=hospiat_user
#spring.datasource.password=123@Hospital
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/ot_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#JWT Secret
jwt.secret=8d#P@f92$Lm!vRzXq1TgB7nKw3uYc^H0zE4rS*J9o

#Billing Base URl
billing.service.url=http://localhost:3005
#billing.service.url=http://147.93.28.8:3005

# -----------------------
# JPA Common
# -----------------------
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



