spring.application.name=OT Management System

# Server
server.port=3010

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/ot
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Live OT DB
#spring.datasource.lab.jdbc-url=jdbc:mysql://localhost:3306/ot_db
#spring.datasource.lab.username=hospiat_user
#spring.datasource.lab.password=123@Hospital
#spring.datasource.lab.driver-class-name=com.mysql.cj.jdbc.Driver


#JWT Secret
jwt.secret=8d#P@f92$Lm!vRzXq1TgB7nKw3uYc^H0zE4rS*J9o

# -----------------------
# JPA Common
# -----------------------
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect