alter table users
MODIFY column role
ENUM(
'SUPER_ADMIN','HOSPITAL_ADMIN','ADMIN','RECEPTIONIST',
'SURGEON','ANESTHESIOLOGIST','DOCTOR','NURSE', 
'SCRUB_NURSE','CIRCULATING_NURSE','ANESTHESIA_NURSE',
'OT_TECHNICIAN','SURGICAL_TECH','ANESTHESIA_TECHNICIAN',
'ORDERLY','OT_ASSISTANT','BILLING_INCHARGE',
'FELLOW','CONSULTANT','RESIDENT','INTERN','STUDENT','OBSERVER'
);